### ISSUE TITLE
Looks like a hang, work around by UNDO

### ISSUE THREAD

**Issue by JoergHW** [uberspot/2048-android#33]
I reached more than 102400 points and still have open spaces. Highest piece is 8192.
The situation is as follows:
Whenever I make a move it won't show up. Further input is impossible (at least it looks like).
I use the UNDO to revert my move, then the previous situation gets shown. Then I can make ONE more move and I have to go through the UNDO loop again. Very annoying.
When starting the app I see a score of 0 and a high score of 0. When using the UNDO my current game board is shown again and I can start with ONE move.

System: Wiko Cink Peax 2, Android 4.1.2 (kernel 3.4.5, build ALPS.JB.SP.V1)

**Comment by Shnoulle** [comment]
Same issue, since we have undo.

System start to be very slow at 4096, start to really hang at 16384. Sometimes quit. Due to a high memory usage.

And last part is : start but show an empty screen. Wait , wait ... never show something.

The issue msut surely be fixed if undo are limited to 10 or a little more step. Actaully : seems we can undo and undo again. Then this must be in memory.
![screenshot_20160310-233427](https://cloud.githubusercontent.com/assets/1439428/13696829/4c162dce-e769-11e5-87af-d3697a0daca2.png)
![screenshot_20160310-233720](https://cloud.githubusercontent.com/assets/1439428/13696830/4c16359e-e769-11e5-972f-bdef9675b071.png)

**Comment by Shnoulle** [comment]
Seems to have build issue : https://gitlab.com/fdroid/fdroiddata/issues/420#note_4213918

**Comment by Shnoulle** [comment]
Closed in 2.06
